[build-system]
requires = ["hatchling>=1.27", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "smriprep"
description = "Structural MRI Preprocessing Pipelines"
readme = "README.rst"
authors = [{name = "The NiPreps Developers", email = "nipreps@gmail.com"}]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.12"
dependencies = [
    "acres >= 0.5.0",
    "indexed_gzip >= 1.8.7",
    "lockfile >= 0.12.2",
    "looseversion >= 1.3.0",
    "matplotlib >= 3.9",
    "nibabel >= 5.3.0",
    "nipype >= 1.9.0",
    "nireports >= 25.3.0",
    "nitransforms >= 25.0.1",
    "niworkflows >= 1.14.4",
    "numpy >= 2.1",
    "packaging >= 24.2",
    "pybids >= 0.21",
    "pyyaml >= 6.0.1",
    "templateflow >= 25.0",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/nipreps/smriprep"
Documentation = "https://nipreps.org/smriprep"
"Docker Images" = "https://hub.docker.com/r/nipreps/smriprep/tags/"
NiPreps = "https://www.nipreps.org/"

[project.optional-dependencies]
datalad = ["datalad"]
doc = [
    "nbsphinx",
    "packaging",
    "pydot",
    "sphinx",
    "sphinx-argparse",
    "sphinx_rtd_theme",
    "sphinxcontrib-apidoc",
    "sphinxcontrib-napoleon",
    "sphinxcontrib-versioning",
]
duecredit = ["duecredit"]
test = [
    "coverage[toml] >= 7.6.2",
    "pytest >= 8.3.3",
    "pytest-cov >= 6.0.0",
    "pytest-env >= 1.1.4",
    "pytest-xdist >= 3.7.0",
]
style = ["flake8"]
# Aliases
docs = ["smriprep[doc]"]
tests = ["smriprep[test]"]
all = ["smriprep[datalad,doc,duecredit,test]"]

[project.scripts]
smriprep = "smriprep.cli.run:main"

#
# Hatch configurations
#

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.sdist]
exclude = [".git_archival.txt"]  # No longer needed in sdist

[tool.hatch.build.targets.wheel]
packages = ["src/smriprep"]

##  The following two sections configure setuptools_scm in the hatch way

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/smriprep/_version.py"

#
# Developer tool configurations
#

[tool.pytest.ini_options]
minversion = "8"
testpaths = ["src", "test"]
log_level = "INFO"
xfail_strict = true
norecursedirs = [".git"]
addopts = [
  "-svx",
  "-ra",
  "--strict-config",
  "--strict-markers",
  "--doctest-modules",
  # Config pytest-cov
  "--cov=src/smriprep",
  "--cov-report=xml",
  "--cov-config=pyproject.toml",
]
doctest_optionflags = "ALLOW_UNICODE NORMALIZE_WHITESPACE ELLIPSIS"
env = "PYTHONHASHSEED=0"
filterwarnings = ["ignore::DeprecationWarning"]
junit_family = "xunit2"

[tool.coverage.run]
branch = true
source = ["smriprep"]
omit = [
    "*/tests/*",
]
relative_files = true

[tool.coverage.paths]
source = [
    "smriprep/",
    "*/site-packages/smriprep",
]

[tool.ruff]
line-length = 99
extend-exclude = [
  "wrapper/*.py",
  "docs/sphinxext/*",
]

[tool.ruff.lint]
extend-select = [
  "F",
  "E",
  "W",
  "I",
  "UP",
  "YTT",
  "S",
  "BLE",
  "B",
  "A",
  # "CPY",
  "C4",
  "DTZ",
  "T10",
  # "EM",
  "EXE",
  "FA",
  "ISC",
  "ICN",
  "PT",
  "Q",
]
ignore = [
  "S311",  # We are not using random for cryptographic purposes
  "S603",
]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.ruff.lint.extend-per-file-ignores]
"*/test_*.py" = ["S101"]
"docs/conf.py" = ["A001"]

[tool.ruff.format]
quote-style = "single"

[tool.codespell]
skip = "*/data/*,*docs/_build/*,*.svg,*docs/_static/*"
